const { GoogleGenAI } = require("@google/genai");

/**
 * Netlify serverless function to proxy requests to the Gemini API.
 * This file uses the CommonJS module syntax (require/exports.handler)
 * for maximum compatibility with the default Node.js Netlify runtime.
 */
exports.handler = async (event) => {
    // 1. Security Check: Only allow POST requests
    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 405,
            body: JSON.stringify({ message: "Method Not Allowed. Use POST." }),
        };
    }

    // 2. Access the API Key securely from the Netlify environment variables
    const apiKey = process.env.GEMINI_API_KEY;

    // Check 2.1: Missing API Key is the highest priority error
    if (!apiKey) {
        console.error("SERVER ERROR: GEMINI_API_KEY environment variable is NOT set in Netlify.");
        return {
            statusCode: 500,
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ 
                message: "NETLIFY CONFIG ERROR: GEMINI_API_KEY environment variable is missing. Check Netlify settings.",
                detail: "API_KEY_MISSING" // Add a specific code for the client to display a helpful message
            }),
        };
    }
    
    let ai;
    try {
        // 3. Initialize the Google GenAI client (using the secure key)
        ai = new GoogleGenAI({ apiKey });
    } catch (e) {
        // This generally only happens if the SDK failed to load entirely.
        console.error("SDK Initialization Error:", e.message, e.stack);
        return {
            statusCode: 500,
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ 
                message: `SDK Initialization Failed. Details: ${e.message}`,
                detail: "SDK_INIT_FAILED"
            }),
        };
    }


    try {
        // 4. Parse the request body
        const { chatHistory, systemPrompt } = JSON.parse(event.body);

        if (!chatHistory || !systemPrompt) {
            return {
                statusCode: 400,
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ message: "Missing required fields (chatHistory or systemPrompt) in the request body." }),
            };
        }

        // 5. Construct the Gemini API payload with Search Grounding
        const generationConfig = {
            tools: [{ google_search: {} }], // Enable grounding
        };

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-preview-09-2025",
            contents: chatHistory,
            config: generationConfig,
            systemInstruction: {
                parts: [{ text: systemPrompt }]
            }
        });

        // 6. Extract results and grounding information
        const candidate = response.candidates?.[0];
        let text = candidate?.content?.parts?.[0]?.text || "No response generated by the model.";
        let sources = [];
        
        const groundingMetadata = candidate?.groundingMetadata;
        if (groundingMetadata && groundingMetadata.groundingAttributions) {
            sources = groundingMetadata.groundingAttributions
                .map(attribution => ({
                    uri: attribution.web?.uri,
                    title: attribution.web?.title,
                }));
        }

        // 7. Return the secure result to the client
        return {
            statusCode: 200,
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ 
                text: text, 
                sources: sources 
            }),
        };

    } catch (error) {
        // Log the detailed error on the server side
        console.error("Gemini API Function Call Error:", error.message, error.stack);

        const status = error.statusCode || 500;
        let detailMessage = "An unknown error occurred during the API call.";
        if (error.message) {
             detailMessage = error.message.includes('API key') 
                ? "API Key issue: The key itself may be invalid or restricted."
                : error.message;
        }

        return {
            statusCode: status,
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ 
                message: `Failed to communicate with the Gemini API. Status: ${status}. Details: ${detailMessage}`,
                detail: "GEMINI_API_FAILED"
            }),
        };
    }
};